// Karl Yerkes implemented core matrix generation and visualization, wrapture functionality, and sequence server
// 2026-05-26

// Code adapted by Eric Rennie with Claude Sonnet 4.6 assistance and generation
// Comments generated by Claude

// Project inspired by and created as a study of Lance Putnam's 'Wrapture'
// https://w2.mat.ucsb.edu/l.putnam/wrapture/index.html

// ── Standard library includes ─────────────────────────────────────────────
#include <array>
#include <fstream>
#include <iostream>
#include <sstream>
#include <vector>

// ── Gamma DSP includes ────────────────────────────────────────────────────
#include "Gamma/Noise.h"
#include "Gamma/Oscillator.h"
#include "Gamma/scl.h"

// ── AlloLib app/GUI/math/UI includes ─────────────────────────────────────
#include "al/app/al_DistributedApp.hpp"
#include "al/app/al_GUIDomain.hpp"
#include "al/math/al_Mat.hpp"
#include "al/math/al_Random.hpp"
#include "al/ui/al_PresetHandler.hpp"
#include "al/ui/al_PresetServer.hpp"
#include "al/ui/al_SequenceServer.hpp"


// Reads an entire text file and returns its contents as a single string.
// Used to load GLSL shader source files from disk at runtime.
std::string slurp(std::string fileName) {
  std::fstream file(fileName);
  std::string returnValue = "";
  while (file.good()) {
    std::string line;
    getline(file, line);
    returnValue += line + "\n";
  }
  return returnValue;
}

using namespace al;

// ─────────────────────────────────────────────────────────────────────────────
// Mat5d
// ─────────────────────────────────────────────────────────────────────────────
// A 5×5 double-precision matrix. The 5th row/column is the homogeneous
// coordinate — always [0,0,0,0,1] — so the top-left 4×4 block is the
// actual linear transform applied to the attractor points.
class Mat5d : public Mat<5, double> {
 public:
  // Fill the matrix with seeded random values in [-1,1], then enforce the
  // homogeneous row constraint (row 4 = [0,0,0,0,1]).
  void coefficients(int seed) {
    rnd::Random<> rng;
    rng.seed(seed);
    for (int k = 0; k < size(); k++) mElems[k] = rng.uniformS();
    mElems[4] = mElems[9] = mElems[14] = mElems[19] = 0;
    mElems[24] = 1;
  }
  // Flatten the matrix into a 25-element array for serialization and blending.
  std::array<double, 25> toArray() {
    std::array<double, 25> a;
    for (int k = 0; k < 25; k++) a[k] = mElems[k];
    return a;
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// wrapture helpers
// ─────────────────────────────────────────────────────────────────────────────

// Core iteration kernel: seeds a random starting point, iterates it through
// matrix m 'count' times, and wraps each coordinate into [-b, b] after every
// step. Appends all points to v. Returns the determinant of m so callers can
// filter out degenerate attractors.
static double wraptureRun(std::vector<Vec4d> &v, double b, Mat5d &m, int seed,
                          int count) {
  rnd::Random<> rng;
  rng.seed(seed);
  Vec5d x(rng.ball<Vec4d>(), 1);
  v.push_back(x.elems());
  for (int i = 0; i < count; i++) {
    x = m * x;
    for (int k = 0; k < x.size() - 1; k++)
      x.elems()[k] = gam::scl::wrap(x.elems()[k], b, -b);
    v.push_back(x.elems());
  }
  return determinant(m);
}

// Build matrix from seed, then run the iteration kernel.
double wrapture(std::vector<Vec4d> &v, double b, int seed, int count) {
  Mat5d m;
  m.coefficients(seed);
  return wraptureRun(v, b, m, seed, count);
}

// Build matrix from a flat 25-element array, then run the iteration kernel.
// Used during blend transitions where the matrix is a lerp of two seeded matrices.
double wraptureFromArray(std::vector<Vec4d> &v, double b,
                         std::array<double, 25> &mat, int seed, int count) {
  Mat5d m;
  for (int k = 0; k < 25; k++) m.elems()[k] = mat[k];
  m.elems()[4] = m.elems()[9] = m.elems()[14] = m.elems()[19] = 0;
  m.elems()[24] = 1;
  return wraptureRun(v, b, m, seed, count);
}

// ─────────────────────────────────────────────────────────────────────────────
// Matrix layout note
// AlloLib Mat<5,double> is column-major: index = col*5 + row.
// Row 4 (homogeneous) is always [0,0,0,0,1] — fixed, not exposed.
// matSliders[row][col] maps to mElems[col*5 + row].
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// Granular synthesis helpers (no Gamma dependency beyond gam::Sine)
// ─────────────────────────────────────────────────────────────────────────────

// Linear attack/decay amplitude envelope for a single grain.
// Internally a three-state machine: IDLE → ATTACK → DECAY → IDLE.
struct GrainEnv {
  float val = 0, inc = 0;
  int atkSamp = 0, dcySamp = 0, remaining = 0;
  enum { IDLE, ATTACK, DECAY } phase = IDLE;

  // Set attack/decay durations and start the envelope from zero.
  void trigger(float atkSec, float dcySec, float sr = 44100.f) {
    atkSamp = std::max(1, (int)(atkSec * sr));
    dcySamp = std::max(1, (int)(dcySec * sr));
    val = 0.f;  inc = 1.f / atkSamp;
    phase = ATTACK;
  }
  // Advance one sample and return the current amplitude; auto-idles at end of decay.
  float operator()() {
    if (phase == IDLE) return 0.f;
    val += inc;
    if (phase == ATTACK && val >= 1.f) {
      val = 1.f;  inc = -1.f / dcySamp;  phase = DECAY;
    } else if (phase == DECAY && val <= 0.f) {
      val = 0.f;  phase = IDLE;
    }
    return val;
  }
  bool done() const { return phase == IDLE; }
};

// A single granular voice: one sine oscillator plus a GrainEnv.
// trigger() sets frequency and envelope shape; operator()() produces one sample
// and deactivates the grain when the envelope finishes.
struct Grain {
  gam::Sine<> osc;
  GrainEnv    env;
  bool active = false;
  void trigger(float hz, float atkSec, float dcySec) {
    osc.freq(hz);
    env.trigger(atkSec, dcySec);
    active = true;
  }
  float operator()() {
    if (!active) return 0.f;
    float s = osc() * env();
    if (env.done()) active = false;
    return s;
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// Resonator — classic 2-pole resonant band-pass (no Gamma dependency)
//   freq : center frequency in Hz
//   res  : pole radius [0,1) — closer to 1 = narrower, longer ring
// ─────────────────────────────────────────────────────────────────────────────
// Classic 2-pole IIR resonant bandpass ("reson") filter.
// set() computes coefficients; operator()(x) filters one sample.
// gain is normalized so the peak response is approximately 1.
struct Resonator {
  float y1 = 0, y2 = 0, a1 = 0, a2 = 0, gain = 1;
  void set(float freq, float res, float sr = 44100.f) {
    float w = 2.f * float(M_PI) * freq / sr;
    a1   = 2.f * res * std::cos(w);
    a2   = -(res * res);
    gain = (1.f - res * res) * 0.5f;  // normalise peak to ~1
  }
  float operator()(float x) {
    float y = gain * x + a1 * y1 + a2 * y2;
    y2 = y1;  y1 = y;
    return y;
  }
};

// ─────────────────────────────────────────────────────────────────────────────
// SimpleReverb — Freeverb-style: 4 comb filters parallel + 2 allpass in series
// ─────────────────────────────────────────────────────────────────────────────
// Freeverb-inspired reverb network.
// 4 comb filters (with internal lowpass damping) run in parallel; their summed
// output passes through 2 allpass filters in series.
// Delay lengths are prime-ish integers tuned for 44100 Hz to avoid resonance overlap.
struct SimpleReverb {
  static constexpr int NC = 4, NA = 2;
  // Delay lengths tuned for 44100 Hz (prime-ish to avoid resonance overlap)
  static constexpr int CD[NC] = {1116, 1188, 1277, 1356};
  static constexpr int AD[NA] = {556, 441};

  std::vector<float> cbuf[NC], abuf[NA];
  int ci[NC]{}, ai[NA]{};
  float cfbk[NC]{}, cstate[NC]{};  // comb feedback + lowpass state
  float damp = 0.4f, afbk = 0.5f;

  // Allocate delay buffers and compute per-comb feedback coefficients from
  // the target decay time in seconds.
  void init(float sr = 44100.f, float decaySec = 4.f) {
    for (int i = 0; i < NC; i++) {
      cbuf[i].assign(CD[i], 0.f);
      cfbk[i] = std::pow(0.001f, CD[i] / (sr * decaySec));
    }
    for (int i = 0; i < NA; i++) abuf[i].assign(AD[i], 0.f);
  }

  // Process one sample through the full comb + allpass network.
  float operator()(float in) {
    float out = 0;
    for (int i = 0; i < NC; i++) {
      float d = cbuf[i][ci[i]];
      cstate[i] = d * (1.f - damp) + cstate[i] * damp;
      cbuf[i][ci[i]] = in + cstate[i] * cfbk[i];
      ci[i] = (ci[i] + 1) % CD[i];
      out += d;
    }
    out *= 0.25f;
    for (int i = 0; i < NA; i++) {
      float d = abuf[i][ai[i]];
      abuf[i][ai[i]] = out + d * afbk;
      ai[i] = (ai[i] + 1) % AD[i];
      out = d - afbk * out;
    }
    return out;
  }
};

struct AlloApp : DistributedApp {


  PresetHandler presetHandler;
  PresetSequencer presetSequencer;
  //ky SequenceServer* sequenceServer{nullptr}; // {"127.0.0.1", 9012};


  // ── Zoo of interesting seeds ──────────────────────────────────────────────
  // Hand-curated seeds whose attractors have distinct visual characters.
  // d: values are the matrix determinant (logged during discovery).
  std::vector<int> zoo = {
      186,  // two flat planes to quad clusters  d:0.311102
      0,    // circles                           d:0.325492
      15,   // galaxy/spirals                    d:0.478628
      99,   // straight lines                    d:0.341211
      7,    // flat planes at 80 degrees         d:0.305452
      11,   // sparse formations with circle     d:0.713958
      76,   // formations with circles           d:0.744726
      77,   // 'wind blowing' effect             d:0.563679
      91,   // triangles                         d:0.335576
      139,  // 'fire' effect                     d:0.512121
      120,  // straight line planes              d:0.680127
      154   // interesting cloud/circle          d:0.421385
  };

  // ── Synced parameters ─────────────────────────────────────────────────────
  // These are broadcast from primary to secondary nodes via OSC through
  // AlloLib's parameterServer — any change on the primary is reflected on all secondaries.
  Parameter b{"b", 1.0, 0.001, 5};
  Parameter r{"r", 0.01, 0.001, 0.031};
  Parameter count{"count", 10000, 1000, 200000};
  ParameterPose camera{"cam"};
  ParameterInt seed{"seed", "", 0, 0, 1000000};
  ParameterInt zooIndex{"zooIndex", "", 0, 0, 100};  // was plain int — now synced
  ParameterBool matEditMode{"matEditMode", "", false};

  // blendActive: primary sets true to tell secondary "start blending".
  // Primary sets false when its own blend settles.
  ParameterBool blendActive{"blendActive", "", false};
    // single-string target matrix to avoid partial updates over OSC
    ParameterString targetMatParam{"targetMat", "network", ""};

  // ── Rotation parameters ───────────────────────────────────────────────────
  // rotSpeed: degrees per frame, controlled via GUI slider.
  // rotAngle: synced each frame from primary so secondaries stay locked.
  Parameter rotSpeed{"rotSpeed", 0.5,    -5.0,    5.0};
  Parameter rotAngle{"rotAngle", 0.0, -1e9f,   1e9f};   // synced accumulator
  Parameter rotX    {"rotX",     0.0,    -1.0,    1.0};
  Parameter rotY    {"rotY",     1.0,    -1.0,    1.0};
  Parameter rotZ    {"rotZ",     0.0,    -1.0,    1.0};
  // Start paused by default
  ParameterBool rotPaused{"rotPaused", "", true};  // checked = freeze rotation

  // ── Inner (differential) spin — GPU-side per-point XY rotation ───────────
  // Each point rotates by innerSpin * dist(from Z axis) degrees, so outer
  // arms sweep faster than the core — galactic differential rotation.
  Parameter innerSpinSpeed{"innerSpinSpeed", 0.0, -10.0, 10.0};
  Parameter innerSpin     {"innerSpin",      0.0, -1e9f, 1e9f};  // accumulator
  ParameterBool innerSpinPaused{"innerSpinPaused", "", true};

  // ── 20 current-matrix sliders: matSliders[row][col] ──────────────────────
  // Each slider represents one element of the editable 4×5 sub-block of the
  // 5×5 matrix. Column-major layout: matSliders[row][col] → mElems[col*5+row].
  Parameter matSliders[4][5] = {
      {{"m00", 0, -1, 1}, {"m01", 0, -1, 1}, {"m02", 0, -1, 1},
       {"m03", 0, -1, 1}, {"m04", 0, -1, 1}},
      {{"m10", 0, -1, 1}, {"m11", 0, -1, 1}, {"m12", 0, -1, 1},
       {"m13", 0, -1, 1}, {"m14", 0, -1, 1}},
      {{"m20", 0, -1, 1}, {"m21", 0, -1, 1}, {"m22", 0, -1, 1},
       {"m23", 0, -1, 1}, {"m24", 0, -1, 1}},
      {{"m30", 0, -1, 1}, {"m31", 0, -1, 1}, {"m32", 0, -1, 1},
       {"m33", 0, -1, 1}, {"m34", 0, -1, 1}},
  };

  // ── 20 target-matrix sliders: targetSliders[row][col] ────────────────────
  // Primary writes these when starting a blend so secondaries know targetMat.
  Parameter targetSliders[4][5] = {
      {{"t00", 0, -1, 1}, {"t01", 0, -1, 1}, {"t02", 0, -1, 1},
       {"t03", 0, -1, 1}, {"t04", 0, -1, 1}},
      {{"t10", 0, -1, 1}, {"t11", 0, -1, 1}, {"t12", 0, -1, 1},
       {"t13", 0, -1, 1}, {"t14", 0, -1, 1}},
      {{"t20", 0, -1, 1}, {"t21", 0, -1, 1}, {"t22", 0, -1, 1},
       {"t23", 0, -1, 1}, {"t24", 0, -1, 1}},
      {{"t30", 0, -1, 1}, {"t31", 0, -1, 1}, {"t32", 0, -1, 1},
       {"t33", 0, -1, 1}, {"t34", 0, -1, 1}},
  };

  // ── Local (non-synced) state ──────────────────────────────────────────────
  bool guiReady = false;      // guards callbacks from firing before init completes
  ShaderProgram shader;
  std::vector<Vec4d> v;       // trajectory point cloud produced by wraptureRun
  std::array<double, 25> currentMat{};  // canonical current 5×5 matrix (flat)
  std::array<double, 25> targetMat{};   // blend destination matrix (flat)
  double blendT = 1.0;       // local blend progress [0,1]; 1.0 = no blend in flight
  double blendSpeed = 0.02;  // fraction of blend completed per frame
  bool dragged = false;      // true for one frame after a mouse drag

  // ── Sonification ──────────────────────────────────────────────────────────
  // Drone: 10 sine partials of A1 (55 Hz), amplitudes shaped by a 4D histogram
  //   of the point cloud — each seed produces a distinct harmonic spectrum.
  // Melody: one sine that walks through v[] each frame, mapping w → pitch in
  //   [55–220 Hz] with a slow legato glide — gives continuous variation.
  static constexpr int NUM_PARTIALS = 20;
  static constexpr float FUNDAMENTAL_HZ = 10.0f;   // A1: partials 55–550 Hz
  gam::Saw<>      partials[NUM_PARTIALS];
  gam::Sine<>      lfos[NUM_PARTIALS];
  gam::Sine<>      melody;                          // wanders through attractor trajectory
  SimpleReverb     reverb;
  float baseFreqs[NUM_PARTIALS]{};      // per-partial fundamental + detune
  float targetAmps[NUM_PARTIALS]{};     // amplitude targets set by histogram
  float smoothAmps[NUM_PARTIALS]{};     // exponentially smoothed toward targetAmps
  float melodyFreqTarget = 55.0f;       // pitch target set by w-walk
  float melodyFreqSmooth = 55.0f;       // smoothed pitch driving melody osc
  float blendEnvelope = 0.0f;           // smooth swell [0,1] while blending
  size_t vWalkIdx = 0;                  // index stepping through v[] for melody
  Parameter audioVolume{"audioVolume", 0.18f, 0.0f, 1.0f};
  Parameter reverbWet{"reverbWet", 0.4f, 0.0f, 1.0f};
  static constexpr float AMP_SMOOTH  = 0.003f;
  static constexpr float FREQ_SMOOTH = 0.0008f;   // melody glide speed
  int lastSeed = -1;  // tracks last seen seed to detect preset-driven changes

  // ── FM Synthesis ──────────────────────────────────────────────────────────
  // 4 operator pairs, one per matrix row. Each row's column values drive:
  //   col 0 → modulator frequency ratio  [0.5 – 3.0]
  //   col 2 → modulation index           [0 – 8]
  //   |col 1| → FM voice amplitude       [0 – 1]
  // displayedMat tracks the live lerped matrix so FM morphs during blends.
  std::array<double, 25> displayedMat{};  // live lerped matrix (follows blend)
  gam::Sine<> fmCarriers[4];
  gam::Sine<> fmMods[4];
  float fmRatioTarget[4]{};   float fmRatio[4]{};   // modulator ratio targets + smoothed
  float fmIndexTarget[4]{};   float fmIndex[4]{};   // modulation index targets + smoothed
  float fmAmpTarget[4]{};     float fmAmp[4]{};     // voice amplitude targets + smoothed
  Parameter fmVolume{"fmVolume", 0.0f, 0.0f, 1.0f};
  static constexpr float FM_SMOOTH = 0.001f;

  // ── Modal resonator bank ──────────────────────────────────────────────────
  // Pink noise through 5 gam::Reson filters (one per matrix column).
  // Each column's mean absolute value maps logarithmically to a center freq
  // in [80, 1500] Hz — the matrix literally becomes a set of resonant modes.
  static constexpr int NUM_RESONATORS = 5;
  gam::NoiseWhite<> resonNoise;
  Resonator        resonators[NUM_RESONATORS];
  float resonFreqTarget[NUM_RESONATORS]{};  // target center freqs from matrix
  float resonFreq[NUM_RESONATORS]{};        // smoothed center freqs driving filters
  Parameter resonVolume{"resonVolume", 0.0f, 0.0f, 1.0f};
  Parameter resonQ{"resonQ", 0.97f, 0.5f, 0.999f};  // pole radius (closer to 1 = narrower)
  static constexpr float RESON_SMOOTH = 0.002f;

  // ── Granular synthesis ────────────────────────────────────────────────────
  // Each grain is a short sine burst (attack + decay) pitched from a w value
  // sampled from v[]. A wRing[] snapshot is filled by onAnimate so onSound
  // can read frequencies without touching v[] across threads.
  static constexpr int MAX_GRAINS  = 16;
  static constexpr int W_RING_SIZE = 2048;
  Grain  grains[MAX_GRAINS];
  float  wRing[W_RING_SIZE]{};    // freq values snapshotted each frame
  int    wRingSize = 0;
  int    grainCounter = 0;        // samples until next grain trigger
  uint32_t grainRng = 12345u;     // fast LCG — audio-thread safe, no stdlib rand
  float  sampleRate = 44100.f;    // cached from onCreate
  Parameter grainVolume{"grainVolume", 0.0f,   0.0f, 1.0f};
  Parameter grainRate  {"grainRate",  30.f,    1.f,  200.f}; // grains/sec
  Parameter grainSize  {"grainSize",  0.04f, 0.005f, 0.25f}; // seconds

  // ─────────────────────────────────────────────────────────────────────────
  // Slider <-> array helpers
  //
  // Both pairs (mat <-> matSliders, target <-> targetSliders) share the same
  // nested-loop shape, so we parameterize over the slider bank and the array.
  // ─────────────────────────────────────────────────────────────────────────

  // Copy a 4×5 slider bank into a flat 25-element array (enforcing homogeneous row).
  std::array<double, 25> slidersToArray(Parameter sliders[4][5],
                                        const std::array<double, 25> &base) {
    std::array<double, 25> a = base;
    for (int row = 0; row < 4; row++)
      for (int col = 0; col < 5; col++)
        a[col * 5 + row] = (double)sliders[row][col].get();
    a[4] = a[9] = a[14] = a[19] = 0.0;
    a[24] = 1.0;
    return a;
  }

  // Copy a flat 25-element array into a 4×5 slider bank.
  // Optionally suppress guiReady so bulk sets don't trigger callbacks.
  void arrayToSliders(const std::array<double, 25> &a, Parameter sliders[4][5],
                      bool guardGui = false) {
    bool prev = guiReady;
    if (guardGui) guiReady = false;
    for (int row = 0; row < 4; row++)
      for (int col = 0; col < 5; col++)
        sliders[row][col].set((float)a[col * 5 + row]);
    if (guardGui) guiReady = prev;
  }

  // Convenience wrappers that preserve the original call-site names.
  void matToSliders()        { arrayToSliders(currentMat, matSliders, /*guardGui=*/true); }
  void targetToTargetSliders() { arrayToSliders(targetMat, targetSliders); }
  std::array<double, 25> slidersToArray()       { return slidersToArray(matSliders,    currentMat); }
  std::array<double, 25> targetSlidersToArray() { return slidersToArray(targetSliders, targetMat);  }

  // ─────────────────────────────────────────────────────────────────────────
  // Rebuild helpers
  // ─────────────────────────────────────────────────────────────────────────

  // Full rebuild from seed (PRIMARY ONLY — searches for valid determinant).
  // Increments seed until the determinant falls in [0.3, 0.95] to avoid
  // degenerate attractors. Prints w-coordinate statistics for diagnostics.
  void rebuild() {
    v.clear();
    double det = wrapture(v, b, seed.get(), count);
    while (det < 0.3 || det > 0.95) {
      seed.set(seed.get() + 1);
      v.clear();
      det = wrapture(v, b, seed.get(), count);
    }
    double mean = 0, minimum = 1e100, maximum = -1e100;
    for (auto &e : v) {
      if (e.w > maximum) maximum = e.w;
      if (e.w < minimum) minimum = e.w;
      mean += e.w;
    }
    mean /= v.size();
    double dev = 0;
    for (auto &e : v) dev += pow(e.w - mean, 2);
    dev = sqrt(dev / v.size());
    printf("seed:%d det:%lf b:%lf min:%lf max:%lf mean:%lf dev:%lf\n",
           int(seed.get()), det, b.get(), minimum, maximum, mean, dev);
    Mat5d m;
    m.coefficients(seed.get());
    currentMat = m.toArray();
  }

  // Rebuild from exact seed without any searching (SECONDARY — deterministic).
  void rebuildFromSeed(int s) {
    v.clear();
    wrapture(v, b, s, count);
    Mat5d m;
    m.coefficients(s);
    currentMat = m.toArray();
  }

  // Rebuild from current slider values (both nodes, for manual edit mode).
  // Resets blendT so no interpolation is applied to the manually set matrix.
  void rebuildFromSliders() {
    auto a = slidersToArray();
    v.clear();
    wraptureFromArray(v, b, a, seed.get(), count);
    currentMat = a;
    blendT = 1.0;
  }

  // Shared handler body for b and count changes (both nodes).
  // Dispatches to the appropriate rebuild path depending on node role and mode.
  void onParamChange() {
    if (!guiReady) return;
    if (matEditMode.get()) {
      rebuildFromSliders();
    } else if (isPrimary()) {
      rebuild();
      matToSliders();
    } else {
      rebuildFromSeed(seed.get());
      matToSliders();
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Zoo navigation (primary only)
  //   delta: +1 = forward, -1 = backward
  //   blend: true = animated lerp, false = immediate snap
  // ─────────────────────────────────────────────────────────────────────────
  void navigateZoo(int delta, bool blend) {
    matEditMode = false;
    int nextIdx = ((zooIndex.get() + delta) + (int)zoo.size()) % (int)zoo.size();
    zooIndex.set(nextIdx);

    if (blend) {
      // Snapshot currentMat into matSliders BEFORE changing seed so the
      // secondary reads the correct FROM endpoint when blendActive fires.
      matToSliders();

      seed.set(zoo[nextIdx]);

      Mat5d m;
      m.coefficients(seed.get());
      targetMat = m.toArray();
      targetToTargetSliders();
      blendActive.set(false);  // reset edge so callback fires again
      blendT = 0.0;
      blendActive.set(true);
      printf("zoo [%d/%lu] seed:%d\n", nextIdx, zoo.size(), (int)seed.get());
    } else {
      seed.set(zoo[nextIdx]);
      blendT = 0.0;
      rebuild();
      matToSliders();
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Save
  // ─────────────────────────────────────────────────────────────────────────
  // Appends the current slider values to saved_matrices.txt as a
  // space-separated row, prefixed with the current seed.
  void saveMatrixToFile() {
    std::ofstream f("saved_matrices.txt", std::ios::app);
    if (!f.is_open()) { printf("ERROR: could not open saved_matrices.txt\n"); return; }
    f << "# seed:" << seed.get() << " (customized)\n";
    f << "mat";
    auto a = slidersToArray();
    for (int k = 0; k < 25; k++) f << " " << a[k];
    f << "\n";
    f.close();
    printf("Matrix saved to saved_matrices.txt\n");
  }

  // ─────────────────────────────────────────────────────────────────────────
  // onInit
  // ─────────────────────────────────────────────────────────────────────────
  // Sets up the GUI (primary only), registers all parameters with the preset
  // handler and parameterServer for OSC sync, and installs all change callbacks.
  void onInit() override {
    if (isPrimary()) {
      //ky sequenceServer = new SequenceServer();
      auto GUIdomain = GUIDomain::enableGUI(defaultWindowDomain());
      auto &gui = GUIdomain->newGUI();

  presetHandler << camera; 
  presetHandler << b << r << count;
  // Include rotation parameters in presets
  presetHandler << rotSpeed << rotPaused << rotX << rotY << rotZ;
  presetHandler << innerSpinSpeed << innerSpinPaused;
  // Also include seed/zooIndex/rotAngle and edit/blend state so presets
  // restore the exact deterministic state and any pending transitions.
  presetHandler << seed << zooIndex << rotAngle << matEditMode << blendActive;
  // Audio parameters — stored and restored per preset
  presetHandler << audioVolume << reverbWet;
  presetHandler << fmVolume;
  presetHandler << resonVolume << resonQ;
  presetHandler << grainVolume << grainRate << grainSize;
      //presetHandler.setVerbose(true);
      //presetHandler.setSubDirectory("");
      presetHandler.setRootPath("./");
      std::cout << "preset handler root path " << presetHandler.getRootPath() << std::endl;
      std::cout << "preset handler getCurrentPath() " << presetHandler.getCurrentPath() << std::endl;

      presetSequencer.registerPresetHandler(presetHandler);

       presetHandler.setMorphTime(2.0); 

      gui.add(presetHandler);

      gui.add(presetSequencer);

      //ky *sequenceServer << presetSequencer;
      //ky sequenceServer->print();


      gui.add(b);
      gui.add(r);
      gui.add(count);
      gui.add(rotSpeed);
      gui.add(rotPaused);
      gui.add(rotX);
      gui.add(rotY);
      gui.add(rotZ);
      gui.add(innerSpinSpeed);
      gui.add(innerSpinPaused);
      gui.add(audioVolume);
      gui.add(reverbWet);
      gui.add(fmVolume);
      gui.add(resonVolume);
      gui.add(resonQ);
      gui.add(grainVolume);
      gui.add(grainRate);
      gui.add(grainSize);

      for (int row = 0; row < 4; row++)
        for (int col = 0; col < 5; col++) {
          gui.add(matSliders[row][col]);
          presetHandler << matSliders[row][col];
          // Any slider drag enables edit mode and immediately rebuilds from sliders.
          matSliders[row][col].registerChangeCallback([this](float) {
            if (!guiReady) return;
            matEditMode = true;
            rebuildFromSliders();
          });
        }

      // Register target sliders so blends/targets are stored as well.
      for (int row = 0; row < 4; row++)
        for (int col = 0; col < 5; col++) {
          presetHandler << targetSliders[row][col];
        }

      // When the user stores a preset via the GUI, the PresetHandler will
      // write the currently-registered parameter values to disk. We need
      // to ensure the canonical matrix (currentMat) is captured in the
      // m00..m34 parameter fields. The PresetHandler only offers a
      // post-store callback, so we use that to snapshot and overwrite the
      // stored preset with up-to-date slider values.
      presetHandler.registerStoreCallback([this](int index, std::string name, void*) {
        // Snapshot the current canonical matrix into the mat sliders
        matToSliders();
        // Build fresh ParameterStates from the currently-registered parameters
        PresetHandler::ParameterStates values;
        for (auto *pmeta : presetHandler.parameters()) {
          std::vector<al::VariantValue> fields;
          pmeta->getFields(fields);
          values[pmeta->getFullAddress()] = fields;
        }
        // Overwrite the preset file with the updated values
        presetHandler.savePresetValues(values, name, true);
        printf("[preset] snapshot and re-saved preset '%s'\n", name.c_str());
      });

      // Seed initial slider values from first zoo entry before first frame.
      Mat5d m;
      m.coefficients(zoo[0]);
      currentMat = m.toArray();
      matToSliders();
    }

    // ── Register everything with parameterServer ───────────────────────────
    parameterServer() << b << r << count << camera;
    parameterServer() << seed << zooIndex << matEditMode << blendActive;
  parameterServer() << targetMatParam;
      // publish the target matrix as a single string so secondaries get a
      // complete endpoint before being triggered to blend.
      {
        std::ostringstream os;
        for (int k = 0; k < 25; k++) {
          if (k) os << ' ';
          os << targetMat[k];
        }
        targetMatParam.set(os.str());
      }
      blendActive.set(false);  // reset edge so callback fires again
      blendT = 0.0;
      blendActive.set(true);
    parameterServer() << rotSpeed << rotAngle << rotX << rotY << rotZ << rotPaused;
    parameterServer() << innerSpinSpeed << innerSpin << innerSpinPaused;

    for (int row = 0; row < 4; row++)
      for (int col = 0; col < 5; col++) {
        parameterServer() << matSliders[row][col];
        parameterServer() << targetSliders[row][col];
      }

    // ── Secondary callbacks ────────────────────────────────────────────────
    // NOTE: these fire on BOTH nodes when OSC arrives; the isPrimary() guard
    // ensures only the secondary acts on remotely-received changes.

    // Mirror the primary's camera pose onto the secondary's navigator.
    camera.registerChangeCallback([this](const Pose& p) {
      nav().set(p);
    });

    // Secondary rebuilds deterministically from the new seed, but only when
    // no blend is in flight (blendActive callback handles the blend case).
    seed.registerChangeCallback([this](int32_t newSeed) {
      if (isPrimary()) return;
      // During a blend the seed changes to the target but we must NOT rebuild
      // yet — the blendActive callback will set both endpoints and kick off the
      // lerp. Only do an immediate rebuild when no blend is in flight.
      if (blendActive.get()) return;
      rebuildFromSeed(newSeed);
      matToSliders();
    });

    // Use the [0][0] callback as a trigger; by the time it fires all 20
    // values have been sent over OSC and are in the sliders.
    matSliders[0][0].registerChangeCallback([this](float) {
      // Use the [0][0] callback as a trigger; by the time it fires all 20
      // values have been sent over OSC and are in the sliders.
      if (isPrimary()) return;
      if (!guiReady) return;
      if (matEditMode.get()) rebuildFromSliders();
    });

    // For robustness, also register on every slider on the secondary.
    for (int row = 0; row < 4; row++)
      for (int col = 0; col < 5; col++) {
        matSliders[row][col].registerChangeCallback([this](float) {
          if (isPrimary()) return;
          if (!guiReady) return;
          if (matEditMode.get()) rebuildFromSliders();
        });
      }

    // blendActive: secondary starts its own blend when primary signals it.
    // Parses the single-string targetMatParam to get the blend destination,
    // then resets blendT to kick off the per-frame interpolation in onAnimate.
    blendActive.registerChangeCallback([this](float active) {
      if (isPrimary()) return;
      if (active > 0.5f) {
        // Parse the single-string target matrix previously sent by primary.
        currentMat = slidersToArray();        // where we are blending FROM
        std::array<double,25> parsed{};
        std::istringstream is(targetMatParam.get());
        for (int k = 0; k < 25; k++) {
          is >> parsed[k];
        }
        targetMat = parsed;  // where we are blending TO
        blendT = 0.0;
      }
    });

    // ── Bug fix: rebuild when b or count changes (both nodes) ─────────────
    // Both parameters trigger identical logic, so they share onParamChange().
    b.registerChangeCallback([this](float) { onParamChange(); });
    count.registerChangeCallback([this](float) { onParamChange(); });

    // Reset innerSpin accumulator to 0 whenever the spin is paused so the
    // original matrix shape is restored immediately.
    innerSpinPaused.registerChangeCallback([this](float paused) {
      if (paused > 0.5f) innerSpin.set(0.f);
    });
  }

  // ─────────────────────────────────────────────────────────────────────────
  // onCreate
  // ─────────────────────────────────────────────────────────────────────────
  // Compiles shaders, initializes all audio oscillators and reverb,
  // performs the first attractor build, and synchronizes the starting camera.
  void onCreate() override {
    shader.compile(slurp("../vertex.glsl"), slurp("../fragment.glsl"),
                   slurp("../geometry.glsl"));
    // Slight detune per partial so adjacent harmonics beat gently.
    // LFOs staggered in rate (0.04–0.15 Hz) and phase so each partial
    // breathes at its own pace — creates slow organic movement.
    for (int n = 0; n < NUM_PARTIALS; n++) {
      float detune = (n % 2 == 0 ? 1.0f : -1.0f) * 0.08f * n;
      baseFreqs[n] = FUNDAMENTAL_HZ * (n + 1) + detune;
      partials[n].freq(baseFreqs[n]);
      float lfoRate = 0.04f + n * 0.012f;
      lfos[n].freq(lfoRate);
      lfos[n].phase((float)n / NUM_PARTIALS);
      smoothAmps[n] = 0.0f;
    }
    melody.freq(55.0f);
    sampleRate = (float)audioIO().framesPerSecond();
    reverb.init(sampleRate, 3.5f);
    Mat5d m;
    // Make near clipping plane smaller so close objects are not clipped
    lens().near(0.01);
    m.coefficients(zoo[0]);
    currentMat = m.toArray();
    targetMat = currentMat;
    seed.set(zoo[0]);
    rebuild();
    matToSliders();

    // ── Bug fix: set identical starting camera on both nodes ──────────────
    // If the primary's nav() default differs from the secondary's (or the
    // primary has been moved), the secondary sees a different view distance.
    // Set a known default here on both nodes so they start in the same place,
    // then immediately push it from the primary so the secondary snaps to it
    // within the first onAnimate frame.
    nav().pos(0, 0, 4);   // place camera 4 units back along Z
    nav().faceToward(Vec3d(0, 0, 0), Vec3d(0, 1, 0));
    if (isPrimary()) {
      camera.set(nav());  // push immediately so secondary doesn't use its own default
    }

    // Ensure rotation starts paused unless a preset overrides it
    // rotPaused default is true; presets will set it when loaded.
    if (!rotPaused.get()) {
      rotPaused.set(true);
    }

    guiReady = true;  // unlock callbacks on BOTH nodes after init
  }

  // ─────────────────────────────────────────────────────────────────────────
  // onKeyDown  (primary only — secondaries have no keyboard)
  // ─────────────────────────────────────────────────────────────────────────
  bool onKeyDown(const Keyboard &k) override {
    if (!isPrimary()) return true;

    if (k.key() == '0') {
      presetSequencer.playSequence("foo");

    } else if (k.key() == ' ') {
      navigateZoo(+1, /*blend=*/false);   // next zoo entry — immediate snap

    } else if (k.key() == Keyboard::BACKSPACE) {
      navigateZoo(-1, /*blend=*/false);   // previous zoo entry — immediate snap

    } else if (k.key() == 'p') {
      navigateZoo(+1, /*blend=*/true);    // next zoo entry — animated blend

    } else if (k.key() == 'o') {
      navigateZoo(-1, /*blend=*/true);    // previous zoo entry — animated blend

    } else if (k.key() == 'l' || k.key() == 'L') {
      // Reset sliders to current seed
      matEditMode = false;
      blendT = 1.0;
      matToSliders();
      printf("Sliders loaded from current seed:%d\n", (int)seed.get());

    } else if (k.key() == 's' || k.key() == 'S') {
      saveMatrixToFile();
    }

    return true;
  }

  // Sets dragged flag for one frame so onAnimate can trigger a rebuild.
  bool onMouseDrag(const Mouse &m) override {
    dragged = true;
    return true;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // onAnimate
  // ─────────────────────────────────────────────────────────────────────────
  // Per-frame logic: advances rotation/spin accumulators, runs the matrix
  // blend lerp, syncs camera between nodes, detects seed changes from preset
  // loads, and computes all audio target parameters from the point cloud.
  void onAnimate(double dt) override {
    // Primary owns the accumulator and pushes it to secondaries every frame.
    // Secondaries receive it via parameterServer — no local increment needed.
    if (isPrimary() && !rotPaused.get()) {
      rotAngle.set(rotAngle.get() + rotSpeed.get());
    if (isPrimary() && !innerSpinPaused.get())
      innerSpin.set(innerSpin.get() + innerSpinSpeed.get());
    }

    // ── Blend transition (both nodes run the same lerp logic) ──────────────
    if (!matEditMode && blendT < 1.0) {
      blendT = std::min(blendT + blendSpeed, 1.0);

      // Linearly interpolate every matrix element between currentMat and targetMat,
      // then enforce the homogeneous row constraint before regenerating points.
      std::array<double, 25> lerpedMat;
      for (int k = 0; k < 25; k++)
        lerpedMat[k] = currentMat[k] * (1.0 - blendT) + targetMat[k] * blendT;
      lerpedMat[4] = lerpedMat[9] = lerpedMat[14] = lerpedMat[19] = 0.0;
      lerpedMat[24] = 1.0;

      displayedMat = lerpedMat;   // FM params follow the live lerp
      v.clear();
      wraptureFromArray(v, b, lerpedMat, seed.get(), count);

      if (blendT >= 1.0) {
        currentMat = targetMat;
        matToSliders();

        if (isPrimary()) {
          // Tell secondaries the blend is done.
          blendActive.set(false);
        } else {
          // Rebuild cleanly from the final seed so the secondary's v matches
          // exactly what the primary computed at blend end.
          rebuildFromSeed(seed.get());
        }
      }
    }

    // Keep displayedMat current when not in a blend
    if (blendT >= 1.0) displayedMat = currentMat;

    // ── Mouse-drag triggered rebuild (primary only) ────────────────────────
    if (isPrimary() && !matEditMode && dragged) {
      dragged = false;
      rebuild();
      matToSliders();
    }

    // ── Camera sync ───────────────────────────────────────────────────────
    if (isPrimary()) {
      if (presetSequencer.running()) {
        // we are playing back camera animations (sequences)
        // so drive the nav() with those poses
        nav().set(camera);
      }
      else {
        // we are driving around the nav() ourselves...
        // save camera pose
        camera.set(nav());
      }
    } else {
      nav().set(camera);
    }

    // ── Seed change detection (primary only) ─────────────────────────────
    // When a preset loads a new seed the primary has no callback that calls
    // rebuild(), so v[] stays stale. Detect the change here and rebuild.
    if (isPrimary() && !matEditMode.get() && blendT >= 1.0) {
      int curSeed = seed.get();
      if (curSeed != lastSeed) {
        lastSeed = curSeed;
        rebuild();
        matToSliders();
      }
    }

    // ── Blend envelope: gentle swell when a transition is running ─────────
    // Rises quickly when blendT < 1 and falls slowly after the blend settles.
    // Used to boost audio volume and amplitude smoothing speed during blends.
    {
      float blendTarget = (blendT < 1.0f) ? 1.0f : 0.0f;
      float rate = (blendTarget > blendEnvelope) ? 0.3f : 0.005f;
      blendEnvelope += rate * (blendTarget - blendEnvelope);
    }

    // ── Sonification: spectral mask + melody walk ─────────────────────────
    if (isPrimary() && !v.empty()) {
      float bv = b.get();

      // Bin x, y, z, w into NUM_PARTIALS slices of [-b, b], sum all 4 dims.
      float counts[NUM_PARTIALS]{};
      for (auto &pt : v) {
        float dims[4] = {(float)pt.x, (float)pt.y, (float)pt.z, (float)pt.w};
        for (float d : dims) {
          float norm = (d + bv) / (2.0f * bv);
          norm = std::max(0.0f, std::min(0.9999f, norm));
          counts[(int)(norm * NUM_PARTIALS)] += 1.0f;
        }
      }
      // Normalize to total count (fraction per bin), then square to sharpen
      // peaks — this makes each seed's spectrum clearly distinct: sparse
      // bins go nearly silent, dense bins stay loud.
      float total = (float)v.size() * 4.0f;
      for (int n = 0; n < NUM_PARTIALS; n++) {
        float frac = counts[n] / total;
        targetAmps[n] = frac * frac * (float)(NUM_PARTIALS * NUM_PARTIALS);
      }

      // Walk through the trajectory one step per frame; the w value of the
      // current point sets the melody pitch — natural variation from the
      // attractor's own dynamics, changes character during blends.
      vWalkIdx = (vWalkIdx + 11) % v.size();
      float w = (float)v[vWalkIdx].w;
      float norm = (w + bv) / (2.0f * bv);
      // Map [0,1] → [55, 220] Hz (A1 to A3, two octaves)
      melodyFreqTarget = 55.0f * std::pow(4.0f, norm);

      // Snapshot w→frequency values into wRing for the grain engine.
      // Map w from [-b,b] → [55, 880] Hz (3 octaves, A1–A5).
      wRingSize = std::min((int)v.size(), W_RING_SIZE);
      for (int i = 0; i < wRingSize; i++) {
        float wv = (float)v[i].w;
        float fn = (wv + bv) / (2.f * bv);
        fn = std::max(0.f, std::min(1.f, fn));
        wRing[i] = 55.f * std::pow(16.f, fn);  // [55, 880] Hz
      }
    }

    // ── FM target params from displayedMat (primary only) ─────────────────
    // Each of the 4 matrix rows drives one FM operator pair:
    //   col 0  → modulator ratio  (maps [-1,1] → [0.5, 3.0])
    //   col 2  → modulation index (maps [-1,1] → [0, 8])
    //   |col 1|→ voice amplitude  (maps [0,1]  → [0, 1])
    if (isPrimary()) {
      for (int row = 0; row < 4; row++) {
        double v0 = displayedMat[0 * 5 + row];  // col 0
        double v1 = displayedMat[1 * 5 + row];  // col 1
        double v2 = displayedMat[2 * 5 + row];  // col 2
        fmRatioTarget[row] = 0.5f + (float)((v0 + 1.0) / 2.0 * 2.5);  // [0.5, 3.0]
        fmIndexTarget[row] = (float)((v2 + 1.0) / 2.0 * 8.0);         // [0, 8]
        fmAmpTarget[row]   = (float)std::abs(v1);                       // [0, 1]
      }
    }

    // ── Resonator center frequencies from matrix column means (primary) ────
    // Each of the 5 columns contributes one resonant mode. The mean absolute
    // value of the 4 row elements in that column is mapped logarithmically to
    // [80, 1500] Hz — columns with large values ring at high frequencies,
    // columns near zero ring deep.
    if (isPrimary()) {
      for (int col = 0; col < NUM_RESONATORS; col++) {
        double mean = 0;
        for (int row = 0; row < 4; row++)
          mean += std::abs(displayedMat[col * 5 + row]);
        mean /= 4.0;
        // Logarithmic map: [0,1] → [80, 1500] Hz
        resonFreqTarget[col] = 80.0f * std::pow(1500.0f / 80.0f, (float)mean);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // onSound — harmonic drone driven by the w-value histogram
  // ─────────────────────────────────────────────────────────────────────────
  // Mixes five synthesis layers per sample: melody sine, harmonic drone,
  // FM operator pairs, modal resonators, and granular cloud.
  // All layers are summed, wet/dry reverb mixed, then soft-clipped with tanh.
  void onSound(AudioIOData &io) override {
    if (!isPrimary()) return;
    float vol = audioVolume.get();
    // Gentle volume swell during blend (1.5× max) — audible but not startling.
    float blendBoost = 1.0f + 0.5f * blendEnvelope;
    // Speed up amplitude smoothing during a blend so the spectral shift is
    // clearly audible rather than lagging behind the visual transition.
    float ampRate = AMP_SMOOTH + blendEnvelope * 0.04f;
    float wet = reverbWet.get();
    float dry = 1.0f - wet;
    while (io()) {
      // Melody: slow legato glide toward the current attractor w-pitch.
      melodyFreqSmooth += FREQ_SMOOTH * (melodyFreqTarget - melodyFreqSmooth);
      melody.freq(melodyFreqSmooth);
      float mel = melody() * vol * blendBoost * 0.25f;

      // Drone: harmonic partials shaped by the 4D histogram.
      // Each partial is amplitude-modulated by its own slow LFO for
      // organic breathing; all partials are summed and scaled.
      float drone = 0.0f;
      for (int n = 0; n < NUM_PARTIALS; n++) {
        smoothAmps[n] += ampRate * (targetAmps[n] - smoothAmps[n]);
        float lfoVal = 0.75f + 0.25f * lfos[n]();
        drone += partials[n]() * smoothAmps[n] * lfoVal;
      }
      drone *= vol * blendBoost * 0.75f / NUM_PARTIALS;

      // FM layer: 4 operator pairs driven by matrix rows.
      // Modulator output scales the carrier's instantaneous frequency,
      // producing sidebands whose density depends on the modulation index.
      float fmOut = 0.0f;
      float fmVol = fmVolume.get();
      if (fmVol > 0.0f) {
        for (int row = 0; row < 4; row++) {
          fmRatio[row] += FM_SMOOTH * (fmRatioTarget[row] - fmRatio[row]);
          fmIndex[row] += FM_SMOOTH * (fmIndexTarget[row] - fmIndex[row]);
          fmAmp[row]   += FM_SMOOTH * (fmAmpTarget[row]   - fmAmp[row]);
          float carrHz = FUNDAMENTAL_HZ * (row + 1);
          float modHz  = carrHz * fmRatio[row];
          fmMods[row].freq(modHz);
          // Classic FM: carrier frequency = fc + index * fm * modulator sample
          fmCarriers[row].freq(carrHz + fmIndex[row] * modHz * fmMods[row]());
          fmOut += fmCarriers[row]() * fmAmp[row];
        }
        fmOut *= fmVol * 0.25f;  // scale: 4 voices summed, keep headroom
      }

      // Modal resonator bank: pink noise excited by 5 column-driven resonators.
      // High resonQ = narrow bandwidth = long ringing modes (like struck metal).
      // Low resonQ  = wide bandwidth  = dense, noisy formants.
      float resonOut = 0.0f;
      float resonVol = resonVolume.get();
      if (resonVol > 0.0f) {
        float q = resonQ.get();
        float noise = resonNoise();
        for (int c = 0; c < NUM_RESONATORS; c++) {
          resonFreq[c] += RESON_SMOOTH * (resonFreqTarget[c] - resonFreq[c]);
          resonators[c].set(resonFreq[c], q);
          resonOut += resonators[c](noise);
        }
        resonOut *= resonVol * 0.2f;
      }

      // Granular cloud: short sine bursts pitched from the attractor trajectory.
      float grainOut = 0.f;
      float grainVol = grainVolume.get();
      if (grainVol > 0.f && wRingSize > 0) {
        // Count down to next grain trigger.
        if (--grainCounter <= 0) {
          int sPerGrain = std::max(1, (int)(sampleRate / grainRate.get()));
          grainCounter = sPerGrain;
          // Find a free grain slot.
          for (int g = 0; g < MAX_GRAINS; g++) {
            if (!grains[g].active) {
              // LCG for thread-safe pseudo-random index into wRing.
              grainRng = grainRng * 1664525u + 1013904223u;
              int idx = (int)(grainRng >> 21) % wRingSize;
              float dur = grainSize.get();
              grains[g].trigger(wRing[idx], dur * 0.3f, dur * 0.7f);
              break;
            }
          }
        }
        for (int g = 0; g < MAX_GRAINS; g++)
          grainOut += grains[g]();
        grainOut *= grainVol / MAX_GRAINS;
      }

      // Sum all layers, apply wet/dry reverb, then soft-clip with tanh to
      // smoothly limit peaks without harsh distortion.
      float s = mel + drone + fmOut + resonOut + grainOut;
      float out = dry * s + wet * reverb(s);
      // Soft clip: tanh smoothly limits peaks without harsh distortion.
      out = std::tanh(out);
      io.out(0) = io.out(1) = out;
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // onDraw
  // ─────────────────────────────────────────────────────────────────────────
  // Renders the point cloud with the custom shader.
  // Applies the accumulated rotation and passes b, r, and innerSpin as
  // uniforms so the vertex shader can normalize coordinates and apply
  // per-point differential spin.
  void onDraw(Graphics &g) override {
    g.shader(shader);
    g.shader().uniform("b", b);
    g.shader().uniform("r", r);
    g.shader().uniform("innerSpin", innerSpin.get());
    g.clear(0);
    g.pushMatrix();
      g.rotate(rotAngle.get(), rotX.get(), rotY.get(), rotZ.get());
      Mesh m{Mesh::POINTS};
      // Raw vertices in [-b,b] space; vertex shader divides by b to normalize.
      for (auto &vertex : v) m.vertex(vertex);
      g.draw(m);
    g.popMatrix();
  }
};

// Entry point — instantiate and start the distributed app.
int main() { AlloApp().start(); }